server:
  port: 8080
message:
  greeting: Hello! Product-service configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8888/eureka/
management:
  security:
    enabled: false