server:
  port: 8000
message:
  greeting: Hello! Product-service configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.55.20.17:8888/eureka/
management:
  security:
    enabled: false